runtime: nodejs16
env: standard
service: default

instance_class: F2
default_expiration: "12h"

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup

automatic_scaling:
  max_instances: 10
  min_instances: 1
  max_idle_instances: 2
  min_idle_instances: 1
  max_concurrent_requests: 80
